### PR TITLE
Tox check with CI on Windows, macOS and Ubuntu

### PR DESCRIPTION
**Pull request by Youw**
Check most build configurations on Windows, macOS and Ubuntu.

Fixes: #104

### CODE REVIEW

**Comment by Youw** [comment]
One of the latest build results:
https://github.com/Youw/cython-hidapi/actions/runs/6842472365

**Comment by Youw** [comment]
Unfortunately macOS check fails miserably, and I don't know why, as the very same steps on clean venv on my mac machine locally works just fine.
Also, the logs strongly suggest not to invoke `setup.py` directly, but I don't know any other way to pass arguments like `--with-system-hidapi`

**Comment by prusnak** [comment]
> Also, the logs strongly suggest not to invoke `setup.py` directly, but I don't know any other way to pass arguments like `--with-system-hidapi`

I pushed ad6c1727d0e971887b9533c066defff2353ab675 so now you can set options also via ENV variables.

**Comment by Youw** [comment]
Hacky. But effective. Will try.

**Comment by Youw** [comment]
A success!
https://github.com/Youw/cython-hidapi/actions/runs/6842858099

**Comment by Youw** [comment]
NOTE: It appears GithubActions has a hard limit of 15 jobs to run by the build matrix.
This one uses 14.
If need more than that - would need to think of some workarounds like definigs a separate jobs or even actions.

**Pull request merged**
