### PR TITLE
Added Sphinx documentation builder and added doc comments

### LINKED ISSUE #106: Basic documentation (ReadTheDocs)
Would it be worthwhile to start documentation of some of the basics?
A [readthedocs.org](readthedocs.org) project based on a simple Sphinx build would be nice.

I'm not sure if Sphinx's `autodoc` would work with a C-based library, but worth a try.

I might make an example soon.

### PR DESCRIPTION
**Pull request by RobertoRoos**
Added Sphinx documentation structure, based on `autodoc`. This fixes #106 

I've tried to get it to build on ReadTheDocs.org, but to no avail. I could not get the hidapi C-library dependency on libusb and libudev to be worked out (neither in pip and conda builds).

We can try again after this RTD issue is tackled: https://github.com/readthedocs/readthedocs-docker-images/issues/114

### CODE REVIEW

**Comment by prusnak** [comment]
Thank you! Documentation deployed to https://trezor.github.io/cython-hidapi/

**Comment by markspan** [comment]
You do amazing work!

**Comment by RobertoRoos** [comment]
Could you add that link also in the ReadMe? And putting the link on https://pypi.org/project/hidapi/ might also be useful.

**Comment by prusnak** [comment]
Added in https://github.com/trezor/cython-hidapi/commit/59f47c630340df8066976403930b3433c285aa50 and https://github.com/trezor/cython-hidapi/commit/2353c9691b24714cc22098061a5758ddf03f1ae2

PyPI will be updated on the next version push

**Pull request merged**
