### PR TITLE
limit cython version used for hidapi 0.7.x

### PR DESCRIPTION
**Pull request by makinbacon21**
Will not build otherwise

### CODE REVIEW

**Comment by makinbacon21** [comment]
whoops needs more tacked onto this...will do more research

**Comment by makinbacon21** [comment]
Nevermind! I just forgot how python deps worked. This compiles fine. My apologies for the confusion.

**Comment by makinbacon21** [comment]
mbed os (extremely popular and industry standard project) relies heavily on 0.7.x on non-Linux platforms and 0.7.x has received a great many updates. It would be trivial to add one more update so it at least compiles.

**Comment by prusnak** [comment]
I am confused, in one post you say there is a problem, in another you say it compiles, then you again say it does not compile.

**Comment by makinbacon21** [comment]
That is my point--mbed OS's Python tools on non-Linux platforms currently do not compile because it relies on cython-hidapi v0.7.x and this version does not compile since the release of Cython 3. See https://github.com/ARMmbed/mbed-os/blob/master/requirements.txt#L20

**Comment by prusnak** [comment]
@makinbacon21 Please tell mbed os maintainers to open an issue in this repo so we can get the latest hidapi building for non-linux mbed os. Using old version is a bad workaround. We should fix the real problem.

**Comment by makinbacon21** [comment]
I'll add an issue--thanks. In the meantime, can we tag .post22 and put on pypi?
Anyway, thank you for your help and work on this project.

**Comment by prusnak** [comment]
I will wait until we know what is the real issue. Maybe it is less work for me to fix it rather than spend my time doing a release for an ancient version.

**Comment by makinbacon21** [comment]
My guess is it's lack of care to update their usage of the interface on their end rather than some unfixed issue on yours. I have opened an issue and if that is unproductive I will fix next week; very busy this week. Thanks again for the help--I'm glad at least a fix is on the official repo so I can direct others to use for the time being.
________________________________

**Pull request merged**
