### PR TITLE
Fixed FreeBSD detection and build.

### PR DESCRIPTION
**Pull request by cederom**
This fixes https://github.com/libusb/hidapi/issues/112.

Signed-off-by: Tomasz 'CeDeROM' CEDRO.

### CODE REVIEW

**Comment by prusnak** [comment]
There is a lot of code reuse - can you refactor in such a way that  `modules = [ Extension('hid', ...` is created just once?

Can you please advise @alexdupre? I am not using FreeBSD.

**Comment by cederom** [comment]
Thank you @prusnak, hope its better now? :-)

**Comment by alexdupre** [comment]
I'm not sure it's necessary to link it against libusb, linking to hidapi lib might be enough if no libusb functions are directly called. Apart this, I don't see issues in the patch (I've not tried it).

**Comment by cederom** [comment]
TANK U =)

**Pull request merged**
